// src/BenhaScooters/DashboardApp/src/app/pages/drivers/driver-details.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { DriverDetails } from '../../models/driver.models';

@Component({
  selector: 'app-driver-details',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="driver-details">
      <div class="header">
        <h1>Driver Details</h1>
        <button class="btn btn-outline" (click)="backToList()">
          ← Back to List
        </button>
      </div>

      @if (loading()) {
        <div class="loading">Loading driver details...</div>
      } @else if (driver()) {
        <div class="content">
          <div class="section">
            <h2>Status Information</h2>
            <div class="info-grid">
              <div class="info-item">
                <label>Status:</label>
                <span [class]="'badge badge-' + getStatusClass(driver()!.onboardingStatus)">
                  {{ driver()!.onboardingStatus }}
                </span>
              </div>
              <div class="info-item">
                <label>Created:</label>
                <span>{{ formatDate(driver()!.createdAt) }}</span>
              </div>
              @if (driver()!.approvedAt) {
                <div class="info-item">
                  <label>Approved:</label>
                  <span>{{ formatDate(driver()!.approvedAt!) }}</span>
                </div>
              }
              @if (driver()!.rejectionReason) {
                <div class="info-item full-width">
                  <label>Rejection Reason:</label>
                  <span class="rejection-reason">{{ driver()!.rejectionReason }}</span>
                </div>
              }
            </div>
          </div>

          @if (driver()!.personalInfo) {
            <div class="section">
              <h2>Personal Information</h2>
              <div class="info-grid">
                <div class="info-item">
                  <label>Full Name:</label>
                  <span>{{ driver()!.personalInfo!.fullName }}</span>
                </div>
                <div class="info-item">
                  <label>National ID:</label>
                  <span>{{ driver()!.personalInfo!.nationalId }}</span>
                </div>
                <div class="info-item">
                  <label>Date of Birth:</label>
                  <span>{{ formatDate(driver()!.personalInfo!.dateOfBirth!) }}</span>
                </div>
                <div class="info-item">
                  <label>City:</label>
                  <span>{{ driver()!.personalInfo!.city }}</span>
                </div>
                <div class="info-item full-width">
                  <label>Address:</label>
                  <span>{{ driver()!.personalInfo!.address }}</span>
                </div>
                <div class="info-item">
                  <label>Emergency Contact:</label>
                  <span>{{ driver()!.personalInfo!.emergencyContactName }}</span>
                </div>
                <div class="info-item">
                  <label>Emergency Phone:</label>
                  <span>{{ driver()!.personalInfo!.emergencyContactPhone }}</span>
                </div>
              </div>
            </div>
          }

          @if (driver()!.vehicle) {
            <div class="section">
              <h2>Vehicle Information</h2>
              <div class="info-grid">
                <div class="info-item">
                  <label>Type:</label>
                  <span>{{ driver()!.vehicle!.vehicleType }}</span>
                </div>
                <div class="info-item">
                  <label>Brand:</label>
                  <span>{{ driver()!.vehicle!.brand }}</span>
                </div>
                <div class="info-item">
                  <label>Model:</label>
                  <span>{{ driver()!.vehicle!.model }}</span>
                </div>
                <div class="info-item">
                  <label>Year:</label>
                  <span>{{ driver()!.vehicle!.year }}</span>
                </div>
                <div class="info-item">
                  <label>Color:</label>
                  <span>{{ driver()!.vehicle!.color }}</span>
                </div>
                <div class="info-item">
                  <label>License Plate:</label>
                  <span>{{ driver()!.vehicle!.licensePlate }}</span>
                </div>
                <div class="info-item">
                  <label>VIN:</label>
                  <span>{{ driver()!.vehicle!.vin }}</span>
                </div>
              </div>
            </div>
          }

          @if (driver()!.documents.length > 0) {
            <div class="section">
              <h2>Documents</h2>
              <div class="documents-grid">
                @for (doc of driver()!.documents; track doc.documentType) {
                  <div class="document-card">
                    <h3>{{ doc.documentType }}</h3>
                    <img [src]="doc.imageUrl" [alt]="doc.documentType" />
                    <div class="document-info">
                      <small>Uploaded: {{ formatDate(doc.uploadedAt) }}</small>
                      @if (doc.expiryDate) {
                        <small>Expires: {{ formatDate(doc.expiryDate!) }}</small>
                      }
                    </div>
                  </div>
                }
              </div>
            </div>
          }

          <div class="actions">
            @if (driver()!.onboardingStatus === 'Pending') {
              <button class="btn btn-success" (click)="approve()" [disabled]="actionLoading()">
                Approve Driver
              </button>
              <button class="btn btn-danger" (click)="showRejectDialog()" [disabled]="actionLoading()">
                Reject Application
              </button>
            }

            @if (driver()!.onboardingStatus === 'Approved') {
              <button class="btn btn-warning" (click)="showBanDialog()" [disabled]="actionLoading()">
                Suspend Driver
              </button>
            }

            @if (driver()!.onboardingStatus === 'Suspended') {
              <button class="btn btn-success" (click)="unsuspend()" [disabled]="actionLoading()">
                Unsuspend Driver
              </button>
            }
          </div>
        </div>

        @if (showRejectForm()) {
          <div class="modal-overlay" (click)="hideRejectDialog()">
            <div class="modal-content" (click)="$event.stopPropagation()">
              <h3>Reject Driver Application</h3>
              <div class="form-group">
                <label>Rejection Reason:</label>
                <textarea
                  class="form-control"
                  [(ngModel)]="rejectionReason"
                  rows="4"
                  placeholder="Provide a reason for rejection..."
                ></textarea>
              </div>
              <div class="modal-actions">
                <button class="btn btn-outline" (click)="hideRejectDialog()">Cancel</button>
                <button
                  class="btn btn-danger"
                  (click)="reject()"
                  [disabled]="!rejectionReason || actionLoading()"
                >
                  Confirm Rejection
                </button>
              </div>
            </div>
          </div>
        }

        @if (showBanForm()) {
          <div class="modal-overlay" (click)="hideBanDialog()">
            <div class="modal-content" (click)="$event.stopPropagation()">
              <h3>Suspend Driver</h3>
              <div class="form-group">
                <label>Suspension Reason:</label>
                <textarea
                  class="form-control"
                  [(ngModel)]="banReason"
                  rows="4"
                  placeholder="Provide a reason for suspension..."
                ></textarea>
              </div>
              <div class="modal-actions">
                <button class="btn btn-outline" (click)="hideBanDialog()">Cancel</button>
                <button
                  class="btn btn-warning"
                  (click)="ban()"
                  [disabled]="!banReason || actionLoading()"
                >
                  Confirm Suspension
                </button>
              </div>
            </div>
          </div>
        }

        @if (actionMessage()) {
          <div class="toast" [class.success]="actionSuccess()" [class.error]="!actionSuccess()">
            {{ actionMessage() }}
          </div>
        }
      }
    </div>
  `,
  styles: [`
    .driver-details {
      padding: 2rem;
      max-width: 1200px;
      margin: 0 auto;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 2rem;
    }

    h1 {
      margin: 0;
      color: #333;
    }

    h2 {
      color: #555;
      margin-bottom: 1rem;
      font-size: 1.3rem;
    }

    .content {
      display: flex;
      flex-direction: column;
      gap: 2rem;
    }

    .section {
      background: white;
      padding: 2rem;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .info-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 1.5rem;
    }

    .info-item {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .info-item.full-width {
      grid-column: 1 / -1;
    }

    .info-item label {
      font-weight: 600;
      color: #666;
      font-size: 0.9rem;
    }

    .info-item span {
      color: #333;
    }

    .rejection-reason {
      padding: 0.75rem;
      background: #fff3cd;
      border-left: 4px solid #ffc107;
      border-radius: 4px;
    }

    .badge {
      display: inline-block;
      padding: 0.25rem 0.75rem;
      border-radius: 12px;
      font-size: 0.85rem;
      font-weight: 500;
      width: fit-content;
    }

    .badge-pending {
      background: #fff3cd;
      color: #856404;
    }

    .badge-approved {
      background: #d4edda;
      color: #155724;
    }

    .badge-rejected {
      background: #f8d7da;
      color: #721c24;
    }

    .badge-suspended {
      background: #d6d8db;
      color: #383d41;
    }

    .documents-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
      gap: 1.5rem;
    }

    .document-card {
      border: 1px solid #ddd;
      border-radius: 8px;
      overflow: hidden;
    }

    .document-card h3 {
      background: #f8f9fa;
      padding: 0.75rem;
      margin: 0;
      font-size: 1rem;
      color: #555;
    }

    .document-card img {
      width: 100%;
      height: 200px;
      object-fit: cover;
    }

    .document-info {
      padding: 0.75rem;
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .document-info small {
      color: #666;
      font-size: 0.85rem;
    }

    .actions {
      display: flex;
      gap: 1rem;
      padding: 1.5rem;
      background: white;
      border-radius: 8px;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    .loading {
      text-align: center;
      padding: 3rem;
      color: #666;
    }

    .btn {
      padding: 0.75rem 1.5rem;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      font-size: 1rem;
      font-weight: 500;
      transition: all 0.2s;
    }

    .btn-outline {
      background: transparent;
      border: 1px solid #ddd;
      color: #666;
    }

    .btn-outline:hover {
      background: #f5f5f5;
    }

    .btn-success {
      background: #28a745;
      color: white;
    }

    .btn-success:hover:not(:disabled) {
      background: #218838;
    }

    .btn-danger {
      background: #dc3545;
      color: white;
    }

    .btn-danger:hover:not(:disabled) {
      background: #c82333;
    }

    .btn-warning {
      background: #ffc107;
      color: #333;
    }

    .btn-warning:hover:not(:disabled) {
      background: #e0a800;
    }

    .btn:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }

    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      display: flex;
      justify-content: center;
      align-items: center;
      z-index: 1000;
    }

    .modal-content {
      background: white;
      padding: 2rem;
      border-radius: 8px;
      max-width: 500px;
      width: 90%;
    }

    .modal-content h3 {
      margin-top: 0;
      color: #333;
    }

    .form-group {
      margin-bottom: 1.5rem;
    }

    .form-group label {
      display: block;
      margin-bottom: 0.5rem;
      font-weight: 600;
      color: #555;
    }

    .form-control {
      width: 100%;
      padding: 0.75rem;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 1rem;
      font-family: inherit;
    }

    .form-control:focus {
      outline: none;
      border-color: #667eea;
      box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
    }

    .modal-actions {
      display: flex;
      gap: 1rem;
      justify-content: flex-end;
    }

    .toast {
      position: fixed;
      bottom: 2rem;
      right: 2rem;
      padding: 1rem 1.5rem;
      border-radius: 4px;
      color: white;
      font-weight: 500;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
      animation: slideIn 0.3s ease-out;
    }

    .toast.success {
      background: #28a745;
    }

    .toast.error {
      background: #dc3545;
    }

    @keyframes slideIn {
      from {
        transform: translateX(100%);
        opacity: 0;
      }
      to {
        transform: translateX(0);
        opacity: 1;
      }
    }
  `]
})
export class DriverDetailsComponent implements OnInit {
  private readonly apiService = inject(ApiService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  driver = signal<DriverDetails | null>(null);
  loading = signal(false);
  actionLoading = signal(false);
  showRejectForm = signal(false);
  showBanForm = signal(false);
  rejectionReason = '';
  banReason = '';
  actionMessage = signal<string | null>(null);
  actionSuccess = signal(false);

  ngOnInit(): void {
    const userId = this.route.snapshot.paramMap.get('id');
    if (userId) {
      this.loadDriver(+userId);
    }
  }

  loadDriver(userId: number): void {
    this.loading.set(true);
    this.apiService.getDriverDetails(userId).subscribe({
      next: (driver) => {
        this.driver.set(driver);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
        this.showMessage('Failed to load driver details', false);
      }
    });
  }

  approve(): void {
    if (!this.driver()) return;

    this.actionLoading.set(true);
    this.apiService.approveDriver(this.driver()!.userId).subscribe({
      next: () => {
        this.actionLoading.set(false);
        this.showMessage('Driver approved successfully', true);
        this.loadDriver(this.driver()!.userId);
      },
      error: () => {
        this.actionLoading.set(false);
        this.showMessage('Failed to approve driver', false);
      }
    });
  }

  reject(): void {
    if (!this.driver() || !this.rejectionReason) return;

    this.actionLoading.set(true);
    this.apiService.rejectDriver(this.driver()!.userId, this.rejectionReason).subscribe({
      next: () => {
        this.actionLoading.set(false);
        this.hideRejectDialog();
        this.showMessage('Driver application rejected', true);
        this.loadDriver(this.driver()!.userId);
      },
      error: () => {
        this.actionLoading.set(false);
        this.showMessage('Failed to reject driver', false);
      }
    });
  }

  ban(): void {
    if (!this.driver() || !this.banReason) return;

    this.actionLoading.set(true);
    this.apiService.banDriver(this.driver()!.userId, this.banReason).subscribe({
      next: () => {
        this.actionLoading.set(false);
        this.hideBanDialog();
        this.showMessage('Driver suspended', true);
        this.loadDriver(this.driver()!.userId);
      },
      error: () => {
        this.actionLoading.set(false);
        this.showMessage('Failed to suspend driver', false);
      }
    });
  }

  unsuspend(): void {
    if (!this.driver()) return;

    this.actionLoading.set(true);
    this.apiService.unbanDriver(this.driver()!.userId).subscribe({
      next: () => {
        this.actionLoading.set(false);
        this.showMessage('Driver unsuspended successfully', true);
        this.loadDriver(this.driver()!.userId);
      },
      error: () => {
        this.actionLoading.set(false);
        this.showMessage('Failed to unsuspend driver', false);
      }
    });
  }

  showRejectDialog(): void {
    this.rejectionReason = '';
    this.showRejectForm.set(true);
  }

  hideRejectDialog(): void {
    this.showRejectForm.set(false);
  }

  showBanDialog(): void {
    this.banReason = '';
    this.showBanForm.set(true);
  }

  hideBanDialog(): void {
    this.showBanForm.set(false);
  }

  showMessage(message: string, success: boolean): void {
    this.actionMessage.set(message);
    this.actionSuccess.set(success);
    setTimeout(() => this.actionMessage.set(null), 3000);
  }

  backToList(): void {
    this.router.navigate(['/drivers']);
  }

  getStatusClass(status: string): string {
    return status.toLowerCase();
  }

  formatDate(dateString: string): string {
    return new Date(dateString).toLocaleDateString();
  }
}

// src/BenhaScooters/ClientApp/src/components/DriverDetails.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate, Link } from 'react-router-dom'
import { adminAPI, type DriverDetails as DriverDetailsType } from '../services/api'
import { AxiosError } from 'axios'

interface DriverDetailsProps {
  onLogout: () => void
}

interface InfoRowProps {
  label: string
  value: string | React.ReactNode
}

function DriverDetails({ onLogout }: DriverDetailsProps) {
  const { driverId } = useParams<{ driverId: string }>()
  const navigate = useNavigate()
  const [driver, setDriver] = useState<DriverDetailsType | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')
  const [actionLoading, setActionLoading] = useState(false)
  const [banReason, setBanReason] = useState('')
  const [showBanModal, setShowBanModal] = useState(false)

  useEffect(() => {
    if (driverId) {
      fetchDriverDetails()
    }
  }, [driverId])

  const fetchDriverDetails = async () => {
    setIsLoading(true)
    try {
      const response = await adminAPI.getDriverDetails(Number(driverId))
      setDriver(response.data)
    } catch (err) {
      setError('Failed to fetch driver details')
      console.error(err)
    } finally {
      setIsLoading(false)
    }
  }

  const handleApprove = async () => {
    if (!confirm('Are you sure you want to approve this driver?')) return

    setActionLoading(true)
    try {
      await adminAPI.approveDriver(Number(driverId))
      alert('Driver approved successfully!')
      navigate('/')
    } catch (err) {
      const axiosError = err as AxiosError<{ message?: string }>
      alert(axiosError.response?.data?.message || 'Failed to approve driver')
    } finally {
      setActionLoading(false)
    }
  }

  const handleBan = async () => {
    if (!banReason.trim()) {
      alert('Please provide a reason for banning')
      return
    }

    setActionLoading(true)
    try {
      await adminAPI.banDriver(Number(driverId), banReason)
      alert('Driver banned successfully!')
      setShowBanModal(false)
      navigate('/')
    } catch (err) {
      const axiosError = err as AxiosError<{ message?: string }>
      alert(axiosError.response?.data?.message || 'Failed to ban driver')
    } finally {
      setActionLoading(false)
    }
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-xl text-gray-600">Loading driver details...</div>
      </div>
    )
  }

  if (error || !driver) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-xl text-red-600">{error || 'Driver not found'}</div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex justify-between items-center">
          <div className="flex items-center space-x-4">
            <Link to="/" className="text-blue-600 hover:text-blue-800">
              ← Back
            </Link>
            <h1 className="text-2xl font-bold text-gray-900">Driver Details</h1>
          </div>
          <button
            onClick={onLogout}
            className="px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg transition duration-200"
          >
            Logout
          </button>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Personal Information */}
          <div className="bg-white rounded-lg shadow-sm p-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Personal Information</h2>
            <div className="space-y-3">
              <InfoRow label="Full Name" value={driver.personalInfo?.fullName || 'N/A'} />
              <InfoRow label="National ID" value={driver.personalInfo?.nationalId || 'N/A'} />
              <InfoRow label="Phone Number" value={driver.personalInfo?.phoneNumber || 'N/A'} />
              <InfoRow label="Email" value={driver.personalInfo?.email || 'N/A'} />
              <div className="py-2 border-b border-gray-100">
                <div className="flex justify-between items-center mb-2">
                  <span className="text-gray-600 font-medium">Status:</span>
                  <span className={`px-3 py-1 rounded-full text-xs font-semibold ${
                    driver.onboardingState.status === 'Approved' ? 'bg-green-100 text-green-800' :
                    driver.onboardingState.status === 'UnderReview' ? 'bg-yellow-100 text-yellow-800' :
                    driver.onboardingState.status === 'Suspended' ? 'bg-red-100 text-red-800' :
                    driver.onboardingState.status === 'Rejected' ? 'bg-red-100 text-red-800' :
                    'bg-gray-100 text-gray-800'
                  }`}>
                    {driver.onboardingState.status}
                  </span>
                </div>
                
                <div className="mt-2">
                  <div className="flex justify-between items-center text-xs text-gray-500 mb-1">
                    <span>Onboarding Progress</span>
                    <span>{driver.onboardingState.progress}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-1.5">
                    <div 
                      className="bg-blue-600 h-1.5 rounded-full" 
                      style={{ width: `${driver.onboardingState.progress}%` }}
                    ></div>
                  </div>
                </div>

                {driver.onboardingState.rejectionReason && (
                  <div className="mt-2 p-2 bg-red-50 border border-red-100 rounded text-sm text-red-700">
                    <span className="font-semibold text-red-900 block">Rejection Reason:</span>
                    {driver.onboardingState.rejectionReason}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Vehicle Information */}
          <div className="bg-white rounded-lg shadow-sm p-6">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Vehicle Information</h2>
            <div className="space-y-3">
              <InfoRow label="Vehicle Type" value={driver.vehicleInfo?.vehicleType || 'N/A'} />
              <InfoRow label="Brand" value={driver.vehicleInfo?.brand || 'N/A'} />
              <InfoRow label="Model" value={driver.vehicleInfo?.model || 'N/A'} />
              <InfoRow label="Color" value={driver.vehicleInfo?.color || 'N/A'} />
              <InfoRow label="License Plate" value={driver.vehicleInfo?.licensePlate || 'N/A'} />
              <InfoRow label="Year" value={driver.vehicleInfo?.year?.toString() || 'N/A'} />
            </div>
          </div>

          {/* Documents */}
          <div className="bg-white rounded-lg shadow-sm p-6 lg:col-span-2">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">Submitted Documents</h2>
            {driver.documents.length === 0 ? (
              <p className="text-gray-500">No documents uploaded yet</p>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {driver.documents.map((doc, index) => (
                  <div key={index} className="border border-gray-200 rounded-lg p-4">
                    <h3 className="font-semibold text-gray-900 mb-2">{doc.type}</h3>
                    {doc.expirationDate && (
                      <p className="text-sm text-gray-500 mb-2">
                        Expires: {new Date(doc.expirationDate).toLocaleDateString()}
                      </p>
                    )}
                    <a
                      href={doc.imageUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-block px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm rounded-lg transition duration-200"
                    >
                      View Document
                    </a>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Actions */}
          {driver.onboardingState.status === 'UnderReview' && (
            <div className="bg-white rounded-lg shadow-sm p-6 lg:col-span-2">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">Actions</h2>
              <div className="flex space-x-4">
                <button
                  onClick={handleApprove}
                  disabled={actionLoading}
                  className="flex-1 bg-green-600 hover:bg-green-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200 disabled:opacity-50"
                >
                  {actionLoading ? 'Processing...' : 'Approve Driver'}
                </button>
                <button
                  onClick={() => setShowBanModal(true)}
                  disabled={actionLoading}
                  className="flex-1 bg-red-600 hover:bg-red-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-200 disabled:opacity-50"
                >
                  Ban Driver
                </button>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* Ban Modal */}
      {showBanModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg p-6 max-w-md w-full">
            <h3 className="text-xl font-semibold text-gray-900 mb-4">Ban Driver</h3>
            <p className="text-gray-600 mb-4">Please provide a reason for banning this driver:</p>
            <textarea
              value={banReason}
              onChange={(e) => setBanReason(e.target.value)}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-transparent outline-none transition mb-4"
              rows={4}
              placeholder="Enter reason..."
            />
            <div className="flex space-x-4">
              <button
                onClick={() => setShowBanModal(false)}
                className="flex-1 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold py-2 px-4 rounded-lg transition duration-200"
              >
                Cancel
              </button>
              <button
                onClick={handleBan}
                disabled={actionLoading}
                className="flex-1 bg-red-600 hover:bg-red-700 text-white font-semibold py-2 px-4 rounded-lg transition duration-200 disabled:opacity-50"
              >
                {actionLoading ? 'Banning...' : 'Confirm Ban'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function InfoRow({ label, value }: InfoRowProps) {
  return (
    <div className="flex justify-between items-center py-2 border-b border-gray-100">
      <span className="text-gray-600 font-medium">{label}:</span>
      <span className="text-gray-900">{value}</span>
    </div>
  )
}

export default DriverDetails
